import turtle
window = turtle.Screen()
window.bgcolor('cyan')
window.title("Вікно")
window.setup(width=500, height=500, startx=0, starty=0)
my_turtle = turtle.Turtle()
my_turtle.forward(100)
my_turtle.left(90)
my_turtle.forward(100)
my_turtle.left(90)
my_turtle.forward(100)
my_turtle.left(90)
my_turtle.forward(100)
my_turtle.left(135)
my_turtle.forward(20)
my_turtle.left(45)
my_turtle.forward(100)
my_turtle.right(90)
my_turtle.forward(100)
my_turtle.right(90)
my_turtle.forward(100)
my_turtle.right(90)
my_turtle.forward(100)
my_turtle.up()
my_turtle.goto(0, 100)
my_turtle.down()
my_turtle.right(135)
my_turtle.forward(20)
my_turtle.up()
my_turtle.goto(100, 0)
my_turtle.down()
my_turtle.forward(20)
my_turtle.up()
my_turtle.goto(100, 100)
my_turtle.down()
my_turtle.forward(20)

turtle.done()
window.mainloop()