import turtle

window = turtle.Screen()
window.title("Повноекранне вікно для черепашки")
window.bgcolor("white")
window.setup(width=1000, height=600, startx=0, starty=0)

my_turtle = turtle.Turtle()
my_turtle.forward(70)
my_turtle.left(45)
my_turtle.forward(40)
my_turtle.left(180)
my_turtle.forward(40)
my_turtle.left(225)
my_turtle.forward(70)
my_turtle.left(315)
my_turtle.forward(40)
my_turtle.left(180)
my_turtle.forward(40)
my_turtle.left(315)
my_turtle.forward(70)
my_turtle.left(225)
my_turtle.forward(40)
my_turtle.left(180)
my_turtle.forward(40)
my_turtle.left(45)
my_turtle.forward(70)
my_turtle.left(135)
my_turtle.forward(40)
my_turtle.left(45)
my_turtle.forward(70)
my_turtle.left(270)
my_turtle.forward(70)
my_turtle.left(270)
my_turtle.forward(70)
my_turtle.left(270)
my_turtle.forward(70)
my_turtle.up()
my_turtle.goto(200, 200)


turtle.done
window.mainloop()