import turtle
screen = turtle.Screen()
my_turtle = turtle.Turtle()
color = screen.textinput('Input', 'Enter color')
my_turtle.pencolor(color)
shape = screen.textinput('Input', 'Enter shape')
my_turtle.shape(shape)
my_turtle.speed(5)
my_turtle.forward(100)
my_turtle.right(90)
my_turtle.speed(10)
my_turtle.forward(100)
my_turtle.right(90)
my_turtle.speed(15)
my_turtle.forward(100)
my_turtle.right(90)
my_turtle.speed(20)
my_turtle.forward(100)
my_turtle.right(90)
turtle.done()
screen.mainloop()
