import turtle
import random


pen = turtle.Turtle()
screen = turtle.Screen()

# battlesship
screen.setup(width=2160, height=800, startx=0, starty=0)
screen.bgcolor("orange")
screen.title("Battleship")


text = screen.textinput("Players", "Enter how many players?(2-4)")


if text == "2":
    pen.penup()
    pen.goto(-550, 220)
    pen.down()
    pen.right(90)
    pen.forward(100)
    pen.left(90)
    pen.forward(1000)
    pen.left(90)
    pen.up()
    pen.forward(100)
    pen.down()
    pen.left(90)
    pen.forward(1000)
    pen.backward(50)
    pen.left(90)
    pen.forward(100)
    pen.left(90)
    pen.forward(950)
    pen.left(90)
    pen.color("white")
    for _ in range(5):
        pen.forward(10)
        pen.up()
        pen.forward(10)
        pen.down()
    pen.left(180)
    pen.color("black")
    for _ in range(5):
        pen.forward(10)
        pen.up()
        pen.forward(10)
        pen.down()
    pen.left(90)
    pen.forward(1)
    pen.left(90)
    pen.color("white")
    for _ in range(5):
        pen.forward(10)
        pen.up()
        pen.forward(10)
        pen.down()
    pen.left(180)
    pen.color("black")
    for _ in range(5):
        pen.forward(10)
        pen.up()
        pen.forward(10)
        pen.down()


elif text == "3":
    pen.penup()
    pen.goto(-550, 220)
    pen.down()
    pen.right(90)
    pen.forward(100)
    pen.left(90)
    pen.forward(1000)
    pen.left(90)
    pen.up()
    pen.forward(100)
    pen.down()
    pen.left(90)
    pen.forward(1000)
    pen.backward(50)
    pen.left(90)
    pen.forward(100)
    pen.left(90)
    pen.forward(950)
    pen.left(90)
    pen.color("white")
    for _ in range(5):
        pen.forward(10)
        pen.up()
        pen.forward(10)
        pen.down()
    pen.left(180)
    pen.color("black")
    for _ in range(5):
        pen.forward(10)
        pen.up()
        pen.forward(10)
        pen.down()
    pen.left(90)
    pen.forward(1)
    pen.left(90)
    pen.color("white")
    for _ in range(5):
        pen.forward(10)
        pen.up()
        pen.forward(10)
        pen.down()
    pen.left(180)
    pen.color("black")
    for _ in range(5):
        pen.forward(10)
        pen.up()
        pen.forward(10)
        pen.down()

    pen.left(90)
    pen.penup()
    pen.goto(-550, 120)
    pen.pendown()
    pen.right(90)
    pen.forward(100)
    pen.left(90)
    pen.forward(1000)
    pen.left(90)
    pen.up()
    pen.forward(100)
    pen.down()
    pen.left(90)
    pen.forward(1000)
    pen.backward(50)
    pen.left(90)
    pen.forward(100)
    pen.left(90)
    pen.forward(950)
    pen.left(90)
    pen.color("white")
    for _ in range(5):
        pen.forward(10)
        pen.up()
        pen.forward(10)
        pen.down()
    pen.left(180)
    pen.color("black")
    for _ in range(5):
        pen.forward(10)
        pen.up()
        pen.forward(10)
        pen.down()
    pen.left(90)
    pen.forward(1)
    pen.left(90)
    pen.color("white")
    for _ in range(5):
        pen.forward(10)
        pen.up()
        pen.forward(10)
        pen.down()
    pen.left(180)
    pen.color("black")
    for _ in range(5):
        pen.forward(10)
        pen.up()
        pen.forward(10)
        pen.down()


elif text == "4":
    pen.penup()
    pen.goto(-550, 220)
    pen.down()
    pen.right(90)
    pen.forward(100)
    pen.left(90)
    pen.forward(1000)
    pen.left(90)
    pen.up()
    pen.forward(100)
    pen.down()
    pen.left(90)
    pen.forward(1000)
    pen.backward(50)
    pen.left(90)
    pen.forward(100)
    pen.left(90)
    pen.forward(950)
    pen.left(90)
    pen.color("white")
    for _ in range(5):
        pen.forward(10)
        pen.up()
        pen.forward(10)
        pen.down()
    pen.left(180)
    pen.color("black")
    for _ in range(5):
        pen.forward(10)
        pen.up()
        pen.forward(10)
        pen.down()
    pen.left(90)
    pen.forward(1)
    pen.left(90)
    pen.color("white")
    for _ in range(5):
        pen.forward(10)
        pen.up()
        pen.forward(10)
        pen.down()
    pen.left(180)
    pen.color("black")
    for _ in range(5):
        pen.forward(10)
        pen.up()
        pen.forward(10)
        pen.down()

    pen.left(90)
    pen.penup()
    pen.goto(-550, 120)
    pen.pendown()
    pen.right(90)
    pen.forward(100)
    pen.left(90)
    pen.forward(1000)
    pen.left(90)
    pen.up()
    pen.forward(100)
    pen.down()
    pen.left(90)
    pen.forward(1000)
    pen.backward(50)
    pen.left(90)
    pen.forward(100)
    pen.left(90)
    pen.forward(950)
    pen.left(90)
    pen.color("white")
    for _ in range(5):
        pen.forward(10)
        pen.up()
        pen.forward(10)
        pen.down()
    pen.left(180)
    pen.color("black")
    for _ in range(5):
        pen.forward(10)
        pen.up()
        pen.forward(10)
        pen.down()
    pen.left(90)
    pen.forward(1)
    pen.left(90)
    pen.color("white")
    for _ in range(5):
        pen.forward(10)
        pen.up()
        pen.forward(10)
        pen.down()
    pen.left(180)
    pen.color("black")
    for _ in range(5):
        pen.forward(10)
        pen.up()
        pen.forward(10)
        pen.down()

    pen.left(90)
    pen.penup()
    pen.goto(-550, 20)
    pen.pendown()
    pen.right(90)
    pen.forward(100)
    pen.left(90)
    pen.forward(1000)
    pen.left(90)
    pen.up()
    pen.forward(100)
    pen.down()
    pen.left(90)
    pen.forward(1000)
    pen.backward(50)
    pen.left(90)
    pen.forward(100)
    pen.left(90)
    pen.forward(950)
    pen.left(90)
    pen.color("white")
    for _ in range(5):
        pen.forward(10)
        pen.up()
        pen.forward(10)
        pen.down()
    pen.left(180)
    pen.color("black")
    for _ in range(5):
        pen.forward(10)
        pen.up()
        pen.forward(10)
        pen.down()
    pen.left(90)
    pen.forward(1)
    pen.left(90)
    pen.color("white")
    for _ in range(5):
        pen.forward(10)
        pen.up()
        pen.forward(10)
        pen.down()
    pen.left(180)
    pen.color("black")
    for _ in range(5):
        pen.forward(10)
        pen.up()
        pen.forward(10)
        pen.down()


    pen.left(90)
    pen.penup()
    pen.goto(-550, -80)
    pen.pendown()
    pen.right(90)
    pen.forward(100)
    pen.left(90)
    pen.forward(1000)
    pen.left(90)
    pen.up()
    pen.forward(100)
    pen.down()
    pen.left(90)
    pen.forward(1000)
    pen.backward(50)
    pen.left(90)
    pen.forward(100)
    pen.left(90)
    pen.forward(950)
    pen.left(90)
    pen.color("white")
    for _ in range(5):
        pen.forward(10)
        pen.up()
        pen.forward(10)
        pen.down()
    pen.left(180)
    pen.color("black")
    for _ in range(5):
        pen.forward(10)
        pen.up()
        pen.forward(10)
        pen.down()
    pen.left(90)
    pen.forward(1)
    pen.left(90)
    pen.color("white")
    for _ in range(5):
        pen.forward(10)
        pen.up()
        pen.forward(10)
        pen.down()
    pen.left(180)
    pen.color("black")
    for _ in range(5):
        pen.forward(10)
        pen.up()
        pen.forward(10)
        pen.down()



screen.mainloop()