# Form implementation generated from reading ui file '3.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(408, 236)
        self.FirstNumber = QtWidgets.QLineEdit(parent=Form)
        self.FirstNumber.setGeometry(QtCore.QRect(40, 30, 111, 31))
        self.FirstNumber.setObjectName("FirstNumber")
        self.HelloLabel = QtWidgets.QLabel(parent=Form)
        self.HelloLabel.setGeometry(QtCore.QRect(160, 170, 221, 41))
        self.HelloLabel.setText("")
        self.HelloLabel.setObjectName("HelloLabel")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(170, 140, 60, 16))
        self.label.setObjectName("label")
        self.Plus = QtWidgets.QPushButton(parent=Form)
        self.Plus.setGeometry(QtCore.QRect(40, 90, 31, 32))
        self.Plus.setObjectName("Plus")
        self.Minus = QtWidgets.QPushButton(parent=Form)
        self.Minus.setGeometry(QtCore.QRect(40, 140, 31, 32))
        self.Minus.setObjectName("Minus")
        self.Multiply = QtWidgets.QPushButton(parent=Form)
        self.Multiply.setGeometry(QtCore.QRect(90, 90, 31, 32))
        self.Multiply.setObjectName("Multiply")
        self.Divine = QtWidgets.QPushButton(parent=Form)
        self.Divine.setGeometry(QtCore.QRect(90, 140, 31, 32))
        self.Divine.setObjectName("Divine")
        self.SecondNumber = QtWidgets.QLineEdit(parent=Form)
        self.SecondNumber.setGeometry(QtCore.QRect(200, 30, 113, 31))
        self.SecondNumber.setObjectName("SecondNumber")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Result:"))
        self.Plus.setText(_translate("Form", "+"))
        self.Minus.setText(_translate("Form", "-"))
        self.Multiply.setText(_translate("Form", "*"))
        self.Divine.setText(_translate("Form", "/"))
